### ISSUE TITLE
after several minutes of work, the script closes with this error

### ISSUE THREAD

**Issue by CrystalBreak** [txlyre/automaton#2]
Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 353, in connect
  File "urllib3\connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001EA99868190>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pixel.w84.vkforms.ru', port=443): Max retries exceeded with url: /HappySanta/slaves/1.0.0/buyFetter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA99868190>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\txlyr\Desktop\Projects\automaton\automaton.py", line 434, in <module>
  File "C:\Users\txlyr\Desktop\Projects\automaton\automaton.py", line 394, in start
  File "C:\Users\txlyr\Desktop\Projects\automaton\automaton.py", line 293, in chain
  File "C:\Users\txlyr\Desktop\Projects\automaton\automaton.py", line 98, in buy_fetter
  File "C:\Users\txlyr\Desktop\Projects\automaton\automaton.py", line 75, in post
  File "requests\api.py", line 119, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pixel.w84.vkforms.ru', port=443): Max retries exceeded with url: /HappySanta/slaves/1.0.0/buyFetter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA99868190>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))
[13140] Failed to execute script automaton

**Comment by txlyre** [comment]
The game server is closed.
